version: '3'
services:
  app:
    image: credit-system  
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: credit-system
    ports:
      - "3307:3306"  
